"use client";
import { FormEvent,useEffect,useMemo,useState } from "react";
import dynamic from "next/dynamic";
import { onIdTokenChanged,signInWithEmailAndPassword,signOut,type User } from "firebase/auth";
import { firebaseAuth } from "@/lib/firebase-client";
import type { DesignConfig } from "@/lib/config";
import type { OrganizerDesignConfig } from "@/lib/organizer";

const Preview3D=dynamic(()=>import("@/components/Preview3D"),{ssr:false,loading:()=> <div className="loading">Building order preview…</div>});
const OrganizerPreview3D=dynamic(()=>import("@/components/OrganizerPreview3D"),{ssr:false,loading:()=> <div className="loading">Building order preview…</div>});
type OrderDesign=DesignConfig|OrganizerDesignConfig;
type Order={id:string;createdAt:string;status:string;customerName:string;email:string;phone:string;shippingMethod?:"sf-express"|"local-mail";shippingLabel?:string;shippingFee?:number;quantity:number;unitPrice?:number;subtotal?:number;totalAmount?:number;currency?:"HKD";notes:string;design:OrderDesign;items?:Array<{design:OrderDesign;quantity:number}>};
function AdminPreview({design}:{design:OrderDesign}){return "productType" in design?<OrganizerPreview3D design={design}/>:<Preview3D design={design}/>}
const statuses=["Submitted","Generating","Pending Review","Awaiting Customer Approval","Confirmed","In Production","Completed","Manual Review Required","Cancelled"];

export default function Admin(){
 const [user,setUser]=useState<User|null>(null);const [authReady,setAuthReady]=useState(false);const [authError,setAuthError]=useState("");const [signingIn,setSigningIn]=useState(false);
 const [orders,setOrders]=useState<Order[]>([]);const [q,setQ]=useState("");const [selected,setSelected]=useState<Order|null>(null);
 async function token(){if(!firebaseAuth.currentUser)throw new Error("Not signed in");return firebaseAuth.currentUser.getIdToken()}
 async function load(){const idToken=await token();const response=await fetch('/api/orders',{headers:{authorization:`Bearer ${idToken}`}});if(response.status===401){await signOut(firebaseAuth);return}if(!response.ok)throw new Error("Could not load orders");setOrders(await response.json())}
 useEffect(()=>onIdTokenChanged(firebaseAuth,next=>{setUser(next);setAuthReady(true);if(next)load().catch(()=>setAuthError("Could not load the production desk."));else{setOrders([]);setSelected(null)}}),[]);
 const shown=useMemo(()=>orders.filter(o=>(o.id+o.customerName+o.design.name).toLowerCase().includes(q.toLowerCase())),[orders,q]);
 async function login(event:FormEvent<HTMLFormElement>){event.preventDefault();setSigningIn(true);setAuthError("");const data=new FormData(event.currentTarget);try{await signInWithEmailAndPassword(firebaseAuth,String(data.get("email")),String(data.get("password")))}catch{setAuthError("The email or password is incorrect.")}finally{setSigningIn(false)}}
 async function status(value:string){if(!selected)return;const idToken=await token();const response=await fetch(`/api/orders/${selected.id}`,{method:'PATCH',headers:{'content-type':'application/json',authorization:`Bearer ${idToken}`},body:JSON.stringify({status:value})});if(!response.ok){setAuthError("The order status could not be updated.");return}await load();setSelected({...selected,status:value})}
 async function downloadModel(){if(!selected)return;const idToken=await token();const count=selected.items?.length??1;for(let index=0;index<count;index++){const response=await fetch(`/api/orders/${selected.id}/model?item=${index}`,{headers:{authorization:`Bearer ${idToken}`}});if(!response.ok){setAuthError(`3MF model ${index+1} is not available.`);return}const url=URL.createObjectURL(await response.blob());const link=document.createElement("a");link.href=url;link.download=index===0?`${selected.id}.3mf`:`${selected.id}-${index+1}.3mf`;link.click();URL.revokeObjectURL(url)}}
 if(!authReady)return <main className="admin-login"><div className="login-card"><p className="eyebrow brand-lockup">THE <span className="brand-accent">ODDMENT</span> CLUB</p><h1>Checking access…</h1></div></main>;
 if(!user)return <main className="admin-login"><form className="login-card" onSubmit={login}><p className="eyebrow">PRODUCTION DESK</p><h1>Admin sign in</h1><p>Sign in with your authorised Firebase account.</p><label>EMAIL<input name="email" type="email" autoComplete="email" required autoFocus/></label><label>PASSWORD<input name="password" type="password" autoComplete="current-password" required/></label>{authError&&<div className="error">{authError}</div>}<button className="continue" disabled={signingIn}>{signingIn?"SIGNING IN…":"SIGN IN"}<span>→</span></button><a href="/name-tag">← Back to name tag studio</a></form></main>;
 return <main className="admin"><nav><a className="brand" href="/">THE <span className="brand-accent">ODDMENT</span> CLUB</a><span>PRODUCTION DESK</span><button className="signout" onClick={()=>signOut(firebaseAuth)}>SIGN OUT</button></nav><header><div><p className="eyebrow">ORDER MANAGEMENT</p><h1>Production desk</h1></div><div className="metrics"><div><strong>{orders.length}</strong><small>TOTAL REQUESTS</small></div><div><strong>{orders.filter(o=>o.status==='Pending Review').length}</strong><small>TO REVIEW</small></div><div><strong>{orders.filter(o=>o.status==='In Production').length}</strong><small>IN PRODUCTION</small></div></div></header>{authError&&<div className="admin-error">{authError}</div>}<section className="adminbody"><div className="orderlist"><input placeholder="Search name or order number…" value={q} onChange={e=>setQ(e.target.value)}/>{shown.length?shown.map(o=><button key={o.id} className={selected?.id===o.id?'active':''} onClick={()=>setSelected(o)}><div><strong>{o.design.name}</strong><small>{o.id} · {o.customerName}</small></div><span className={`status ${o.status.replaceAll(' ','-').toLowerCase()}`}>{o.status}</span></button>):<p className="empty">No orders yet.</p>}</div><div className="orderdetail">{selected?<><div className="detailhead"><div><p className="eyebrow">{selected.id}</p><h2>{selected.design.name}</h2></div><button className="download" onClick={downloadModel}>DOWNLOAD 3MF ↓</button></div><div className="admin-preview"><div className="preview-top"><span>ORDER 3D PREVIEW</span><span>DRAG TO ROTATE · SCROLL TO ZOOM</span></div><AdminPreview design={selected.design}/></div><div className="detailgrid"><div><small>CUSTOMER</small><strong>{selected.customerName}</strong><a href={`mailto:${selected.email}`}>{selected.email}</a><span>{selected.phone}</span></div><div><small>DESIGN</small>{"productType" in selected.design?<><strong>{selected.design.name}</strong><span>{selected.design.width} × {selected.design.depth} × {selected.design.height} mm</span><span>Colour {selected.design.color}</span></>:<><strong>{selected.design.font}</strong><span>Base {selected.design.baseColor}</span><span>Face {selected.design.topColor}</span></>}</div><div><small>ORDER</small><strong>Quantity {selected.quantity}</strong><span>{selected.shippingLabel??"Shipping not recorded"}{selected.shippingFee!=null?" · HK$"+selected.shippingFee:""}</span><span>{new Date(selected.createdAt).toLocaleString('en-HK')}</span></div></div>{selected.notes&&<div className="notes"><small>CUSTOMER NOTES</small><p>{selected.notes}</p></div>}<label className="statusselect">PRODUCTION STATUS<select value={selected.status} onChange={e=>status(e.target.value)}>{statuses.map(s=><option key={s}>{s}</option>)}</select></label></>:<div className="emptydetail"><span>✦</span><h2>Select an order</h2><p>Review the customer details and download its production model.</p></div>}</div></section></main>
}
