import JSZip from "jszip";
import { BufferGeometry } from "three";
import { DesignConfig } from "./config";
import { createTagGeometry } from "./geometry";
import { saveModel } from "./store";

type Mesh={v:number[][];t:number[][]};
function box(x:number,y:number,z:number,w:number,h:number,d:number):Mesh{const v=[[x,y,z],[x+w,y,z],[x+w,y+h,z],[x,y+h,z],[x,y,z+d],[x+w,y,z+d],[x+w,y+h,z+d],[x,y+h,z+d]];const t=[[0,2,1],[0,3,2],[4,5,6],[4,6,7],[0,1,5],[0,5,4],[1,2,6],[1,6,5],[2,3,7],[2,7,6],[3,0,4],[3,4,7]];return{v,t}}
function merge(items:Mesh[]):Mesh{const v:number[][]=[],t:number[][]=[];for(const m of items){const o=v.length;v.push(...m.v);t.push(...m.t.map(a=>a.map(i=>i+o)))}return{v,t}}
function geometryMesh(g:BufferGeometry):Mesh{const p=g.getAttribute("position");const v:number[][]=[];const t:number[][]=[];const welded=new Map<string,number>();const vertex=(sourceIndex:number)=>{const point=[p.getX(sourceIndex),p.getY(sourceIndex),p.getZ(sourceIndex)];const key=point.map(value=>Math.round(value*100000)).join(",");const existing=welded.get(key);if(existing!==undefined)return existing;const index=v.length;v.push(point);welded.set(key,index);return index};const source=g.index?Array.from({length:g.index.count},(_,i)=>g.index!.getX(i)):Array.from({length:p.count},(_,i)=>i);for(let i=0;i<source.length;i+=3){const triangle=[vertex(source[i]),vertex(source[i+1]),vertex(source[i+2])];if(new Set(triangle).size===3)t.push(triangle)}return{v,t}}
function xmlMesh(m:Mesh){return `<mesh><vertices>${m.v.map(v=>`<vertex x="${v[0]}" y="${v[1]}" z="${v[2]}"/>`).join("")}</vertices><triangles>${m.t.map(t=>`<triangle v1="${t[0]}" v2="${t[1]}" v3="${t[2]}"/>`).join("")}</triangles></mesh>`}
export async function generate3mf(id:string,design:DesignConfig){const geometry=createTagGeometry(design);const base=merge([geometryMesh(geometry.base),geometryMesh(geometry.ring)]);const top=geometryMesh(geometry.face);geometry.base.dispose();geometry.face.dispose();geometry.ring.dispose();const model=`<?xml version="1.0" encoding="UTF-8"?><model unit="millimeter" xml:lang="en-US" xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02"><metadata name="Title">${id} — ${design.name}</metadata><metadata name="Description">True 3.5 mm vector contour base; review in Bambu Studio before slicing</metadata><resources><basematerials id="1"><base name="Base ${design.baseColor}" displaycolor="${design.baseColor.slice(1)}FF"/><base name="Face ${design.topColor}" displaycolor="${design.topColor.slice(1)}FF"/></basematerials><object id="2" type="model" pid="1" pindex="0">${xmlMesh(base)}</object><object id="3" type="model" pid="1" pindex="1">${xmlMesh(top)}</object><object id="4" type="model" name="${id}"><components><component objectid="2"/><component objectid="3"/></components></object></resources><build><item objectid="4"/></build></model>`;const zip=new JSZip();zip.file("[Content_Types].xml",`<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="model" ContentType="application/vnd.ms-package.3dmanufacturing-3dmodel+xml"/></Types>`);zip.file("_rels/.rels",`<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Target="/3D/3dmodel.model" Id="rel0" Type="http://schemas.microsoft.com/3dmanufacturing/2013/01/3dmodel"/></Relationships>`);zip.file("3D/3dmodel.model",model);const data=await zip.generateAsync({type:"nodebuffer",compression:"DEFLATE"});await saveModel(id,data)}
